### PR TITLE
replaced epochIndex to epochNumber

### PR DESCRIPTION
**Pull request by metadimensions**
## Related GitHub Issue

https://github.com/sector-3/protocol/issues/45

## How Has This Been Tested?

Code Edits only

## Sector#3 Contribution

- [ ] Reported contribution at https://goerli.sector3.xyz/v0/priorities/0x6660626F3b51c0A7a9C558Ade45B17B7De6f91c1

### CODE REVIEW

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
Looks like the `getEpochIndex()` function was not refactored?

**Comment by kushalnl7** [comment]
Hi, @aahna-ashina @metadimensions, can I contribute to this PR with a commit for the modification mentioned by @aahna-ashina?

**Comment by aahna-ashina** [comment]
> Hi, @aahna-ashina @metadimensions, can I contribute to this PR with a commit for the modification mentioned by @aahna-ashina?

@kushalnl7 There is a lot of refactoring going on right now, so it would be better if you create a new branch (and pull request) for your changes 😄

**Comment by metadimensions** [comment]
@aahna-ashina refactored now you can review it.

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
@metadimensions Your branch still has conflicts that need to be solved before we can review.

**Comment by aahna-ashina** [comment]
Superseded by https://github.com/sector-3/protocol/pull/68

**Pull request closed without merging**
